openapi: 3.2.0
info:
  title: SpringServe UI Curated Marketplaces API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Curated Marketplaces
paths:
  /api/v1/curated_marketplaces:
    get:
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/curated_marketplace_create_simple'
              full:
                $ref: '#/components/examples/curated_marketplace_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_post
  /api/v1/curated_marketplaces/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_id_get
    patch:
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/curated_marketplace_update_simple'
              full:
                $ref: '#/components/examples/curated_marketplace_update_full'
        required: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_id_patch
    delete:
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_id_delete
  /api/v1/curated_marketplaces/global:
    get:
      summary: Show curated_marketplaces across all accounts
      description: Show minimal information (id, name, is_active) about all curated_marketplaces across all accounts
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_global_get
  /api/v1/curated_marketplaces/permissions:
    get:
      summary: Collection Permissions
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_permissions_get
  /api/v1/curated_marketplaces/{id}/permissions:
    get:
      summary: Permissions Member
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Curated Marketplaces
      operationId: curated_marketplaces_id_permissions_get
components:
  examples:
    curated_marketplace_create_simple:
      summary: Simple
      value:
        name: Curated Marketplace Name
        supply_partner_id: 1
        rate: 1.11
    curated_marketplace_update_simple:
      summary: Simple
      value:
        name: Curated Marketplace Name
        is_active: true
    curated_marketplace_update_full:
      summary: Full
      value:
        name: Curated Marketplace Name
        selling_strategy_name: Selling Strategy Name
        rate: 1.11
        rate_currency: USD
        bulk_add_enabled: true
        rpm_floor: 1.11
        optimization_active: false
        optimization_learn_pct: 1
        optimization_version: 1
        optimization_mode: black_box
        optimization_settings:
          metric: fill_rate
          lookback_minutes: '60'
        supply_allocation: 1
        custom_supply_allocation: false
        waterfall_management: demand_tag
        is_country_white_list: true
        country_codes:
        - US
        obfuscate_ip_address_enabled: false
        obfuscate_latlon_enabled: false
        tier_breakout_enabled: false
        note: note
        is_active: true
    curated_marketplace_create_full:
      summary: Full
      value:
        name: Curated Marketplace Name
        supply_partner_id: 1
        selling_strategy_name: Selling Strategy Name
        revenue_model_type: 0
        rate: 1.11
        rate_currency: USD
        supply_tag_type: 1
        bulk_add_enabled: true
        rpm_floor: 1.11
        optimization_active: false
        optimization_learn_pct: 1
        optimization_version: 1
        optimization_mode: black_box
        optimization_settings:
          metric: fill_rate
          lookback_minutes: '60'
        supply_allocation: 1
        custom_supply_allocation: false
        waterfall_management: demand_tag
        is_country_white_list: true
        country_codes:
        - US
        obfuscate_ip_address_enabled: false
        obfuscate_latlon_enabled: false
        tier_breakout_enabled: false
        note: note
        is_active: true
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
