openapi: 3.2.0
info:
  title: SpringServe UI Changelogs API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Changelogs
paths:
  /api/v1/changelogs:
    get:
      summary: Index
      description: List changelogs. Query parameters time (recommended), change_type, and user filter results. Available for ClearLine account types.
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - name: time
        in: query
        schema:
          $ref: '#/components/schemas/ChangelogsTimeFilter'
      - name: user
        in: query
        description: "Filter by user email, or special keywords: 'Optimization Only', 'Exclude Optimization', 'SpringCleaning Only', \n'Exclude SpringCleaning', 'DirectConnect Only', 'Exclude DirectConnect', 'DataMigration Only', 'Exclude DataMigration',\n'Exclude System Updates', 'High Volume Users Only' and 'Exclude High Volume Users'\n"
        schema:
          type: string
      - name: change_type
        in: query
        schema:
          type: string
          enum:
          - created
          - updated
          - deleted
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Changelogs
      operationId: changelogs_get
  /api/v1/changelogs/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Changelogs
      operationId: changelogs_id_get
  /api/v1/changelogs/user_emails:
    get:
      summary: User Emails
      description: Get the list of User Emails to show for filtering changelogs by user
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Changelogs
      operationId: changelogs_user_emails_get
  /api/v1/changelogs/versioned_types_for_current_account:
    get:
      summary: versioned_types for the Current Account
      description: Returns which versioned_types (and their display names) are applicable for the current account context
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Changelogs
      operationId: changelogs_versioned_types_for_current_account_get
  /api/v1/changelogs/versioned_type/{versioned_type}:
    get:
      summary: Get By Type
      parameters:
      - name: versioned_type
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: number
      - name: per
        in: query
        schema:
          type: number
      - name: search
        in: query
        description: Searches by version change id and summary
        schema:
          type: string
      - name: time
        in: query
        schema:
          $ref: '#/components/schemas/ChangelogsTimeFilter'
      - name: user
        in: query
        description: all/exclude_system_updates/each_user
        schema:
          type: string
      - name: change_type
        in: query
        description: created/updated/deleted
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Changelogs
      operationId: changelogs_versioned_type_versioned_type_get
  /api/v1/changelogs/versioned_type/{versioned_type}/{versioned_id}:
    get:
      summary: Get By Type and Id
      parameters:
      - name: versioned_type
        in: path
        required: true
        schema:
          type: string
      - name: versioned_id
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: number
      - name: per
        in: query
        schema:
          type: number
      - name: search
        in: query
        description: Searches by version change id and summary
        schema:
          type: string
      - name: time
        in: query
        schema:
          $ref: '#/components/schemas/ChangelogsTimeFilter'
      - name: user
        in: query
        description: all/exclude_system_updates/each_user
        schema:
          type: string
      - name: change_type
        in: query
        description: created/updated/deleted
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Changelogs
      operationId: changelogs_versioned_type_versioned_type_versioned_id_get
components:
  schemas:
    ChangelogsTimeFilter:
      type: string
      enum:
      - last_year
      - today
      - yesterday
      - last_7_days
      - last_30_days
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
