openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Audios API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Audios
paths:
  /api/v0/audios:
    get:
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ref/schemas.yaml#/components/schemas/ListResponse
      tags:
      - Audios
      operationId: audios_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/audio_creative_create_simple'
              full:
                $ref: '#/components/examples/audio_creative_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Audios
      operationId: audios_post
  /api/v0/audios/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Audios
      operationId: audios_id_get
    put:
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/audio_creative_update_simple'
              full:
                $ref: '#/components/examples/audio_creative_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Audios
      operationId: audios_id_put
    delete:
      summary: Destroy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - Audios
      operationId: audios_id_delete
components:
  examples:
    audio_creative_update_simple:
      summary: Simple
      value:
        name: Audio Creative Name
        active: true
    audio_creative_update_full:
      summary: Full
      value:
        name: Audio Creative Name
        code: audio-code
        secondary_code: audio-secondary
        advertiser_domain: example.com
        iab_tier_1_category_codes:
        - IAB1
        iab_tier_2_category_codes:
        - IAB1-1
        line_item_demand_tag_ids:
        - 1
        country_source: list
        country_list_ids:
        - 1
        state_source: list
        state_list_ids:
        - 1
        city_source: list
        city_list_ids:
        - 1
        metro_area_source: list
        metro_area_list_ids:
        - 1
        postal_code_source: list
        postal_code_list_ids:
        - 1
        key_value_targeting: true
        budget_timezone: America/New_York
        start_date: '2026-01-01'
        end_date: '2026-12-31'
        flight_dates_timezone: America/New_York
        tag_pixels:
        - pixel_type: AdImpression
          pixel_url: https://pixel.example.com/imp
          pixel_format: image
        active: true
    audio_creative_create_simple:
      summary: Simple
      value:
        name: Audio Creative Name
        demand_partner_id: 1
        creative_remote_url: https://example.com/audio.mp3
    audio_creative_create_full:
      summary: Full
      value:
        name: Audio Creative Name
        demand_partner_id: 1
        creative_remote_url: https://example.com/audio.mp3
        code: audio-code
        secondary_code: audio-secondary
        advertiser_domain: example.com
        iab_tier_1_category_codes:
        - IAB1
        iab_tier_2_category_codes:
        - IAB1-1
        line_item_demand_tag_ids:
        - 1
        country_source: list
        country_list_ids:
        - 1
        state_source: list
        state_list_ids:
        - 1
        city_source: list
        city_list_ids:
        - 1
        metro_area_source: list
        metro_area_list_ids:
        - 1
        postal_code_source: list
        postal_code_list_ids:
        - 1
        key_value_targeting: true
        budget_timezone: America/New_York
        start_date: '2026-01-01'
        end_date: '2026-12-31'
        flight_dates_timezone: America/New_York
        tag_pixels:
        - pixel_type: AdImpression
          pixel_url: https://pixel.example.com/imp
          pixel_format: image
        active: true
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
