openapi: 3.2.0
info:
  title: SpringServe UI Scanned Creative Lists API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Scanned Creative Lists
paths:
  /api/v1/scanned_creative_lists:
    get:
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/scanned_creative_list_create_simple'
              full:
                $ref: '#/components/examples/scanned_creative_list_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_post
  /api/v1/scanned_creative_lists/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_get
    patch:
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/scanned_creative_list_update_simple'
              full:
                $ref: '#/components/examples/scanned_creative_list_update_full'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_patch
    delete:
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_delete
  /api/v1/scanned_creative_lists/permissions:
    get:
      summary: Collection Permissions
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_permissions_get
  /api/v1/scanned_creative_lists/{id}/creatives:
    get:
      summary: Creatives
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_get
  /api/v1/scanned_creative_lists/{id}/permissions:
    get:
      summary: Permissions Member
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_permissions_get
  /api/v1/scanned_creative_lists/{id}/creatives/bulk_create:
    post:
      summary: Add Creatives
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/scanned_creative_list_creatives_bulk_create_single'
              multiple:
                $ref: '#/components/examples/scanned_creative_list_creatives_bulk_create_multiple'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_bulk_create_post
  /api/v1/scanned_creative_lists/{id}/creatives/bulk_delete:
    delete:
      summary: Delete Creatives
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              vast_hashes:
              - abc123def456
            schema:
              type: object
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_bulk_delete_delete
  /api/v1/scanned_creative_lists/{id}/creatives/bulk_replace:
    post:
      summary: Replace Creatives
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/scanned_creative_list_creatives_bulk_replace_single'
              multiple:
                $ref: '#/components/examples/scanned_creative_list_creatives_bulk_replace_multiple'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_bulk_replace_post
  /api/v1/scanned_creative_lists/{id}/creatives/file_bulk_create:
    post:
      summary: Add Creatives (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_file_bulk_create_post
  /api/v1/scanned_creative_lists/{id}/creatives/file_bulk_delete:
    delete:
      summary: Delete Creatives (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_file_bulk_delete_delete
  /api/v1/scanned_creative_lists/{id}/creatives/file_bulk_replace:
    post:
      summary: Replace Creatives (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Scanned Creative Lists
      operationId: scanned_creative_lists_id_creatives_file_bulk_replace_post
components:
  examples:
    scanned_creative_list_creatives_bulk_create_multiple:
      summary: Multiple
      value:
        vast_hashes:
        - abc123def456
        - def456ghi789
        - ghi789jkl012
    scanned_creative_list_create_full:
      summary: Full
      value:
        name: Scanned Creative List Name
        description: Scanned creative list description
        is_active: true
    scanned_creative_list_creatives_bulk_replace_single:
      summary: Single
      value:
        vast_hashes:
        - abc123def456
    scanned_creative_list_update_full:
      summary: Full
      value:
        name: Scanned Creative List Name
        description: Scanned creative list description
        is_active: true
    scanned_creative_list_creatives_bulk_replace_multiple:
      summary: Multiple
      value:
        vast_hashes:
        - abc123def456
        - def456ghi789
        - ghi789jkl012
    scanned_creative_list_create_simple:
      summary: Simple
      value:
        name: Scanned Creative List Name
    scanned_creative_list_creatives_bulk_create_single:
      summary: Single
      value:
        vast_hashes:
        - abc123def456
    scanned_creative_list_update_simple:
      summary: Simple
      value:
        name: Scanned Creative List Name
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
