openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Bid Maps API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Bid Maps
paths:
  /api/v0/bid_maps:
    get:
      summary: Index (alias)
      description: Alias for /api/v0/hb_bid_maps
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ref/schemas.yaml#/components/schemas/ListResponse
      tags:
      - Bid Maps
      operationId: bid_maps_get
    post:
      summary: Create (alias)
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              bid_map_create_simple:
                $ref: '#/components/examples/bid_map_create_simple'
              bid_map_create_full:
                $ref: '#/components/examples/bid_map_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Bid Maps
      operationId: bid_maps_post
  /api/v0/bid_maps/{id}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Show (alias)
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Bid Maps
      operationId: bid_maps_id_get
    put:
      summary: Update (alias)
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              bid_map_update_simple:
                $ref: '#/components/examples/bid_map_update_simple'
              bid_map_update_full:
                $ref: '#/components/examples/bid_map_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Bid Maps
      operationId: bid_maps_id_put
    patch:
      summary: Update (alias)
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              bid_map_update_simple:
                $ref: '#/components/examples/bid_map_update_simple'
              bid_map_update_full:
                $ref: '#/components/examples/bid_map_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Bid Maps
      operationId: bid_maps_id_patch
    delete:
      summary: Destroy (alias)
      responses:
        '204':
          description: No content
      tags:
      - Bid Maps
      operationId: bid_maps_id_delete
components:
  examples:
    bid_map_create_simple:
      summary: Simple
      value:
        name: Bid Map Name
        bid_platform: amazon
        hb_bid_map_type: inventory_split
    bid_map_update_full:
      summary: Full
      value:
        name: Bid Map Name
        description: Updated description
        hb_bid_map_entries:
        - parameter_value: ott3_4035_30
          bid_floor: 1.11
    bid_map_create_full:
      summary: Full
      value:
        name: Bid Map Name
        bid_platform: amazon
        hb_bid_map_type: paid
        description: Bid Map description
        hb_bid_map_entries:
        - parameter_value: ott1_4033_30
          bid_floor: 1.11
        - parameter_value: ott2_4034_60
          bid_floor: 2.22
    bid_map_update_simple:
      summary: Simple
      value:
        name: Bid Map Name
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
