openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Value Lists API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Value Lists
paths:
  /api/v0/value_lists:
    get:
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ref/schemas.yaml#/components/schemas/ListResponse
      tags:
      - Value Lists
      operationId: value_lists_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/value_list_create_simple'
              full:
                $ref: '#/components/examples/value_list_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Value Lists
      operationId: value_lists_post
  /api/v0/value_lists/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Value Lists
      operationId: value_lists_id_get
    put:
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/value_list_update_simple'
              full:
                $ref: '#/components/examples/value_list_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Value Lists
      operationId: value_lists_id_put
    delete:
      summary: Destroy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - Value Lists
      operationId: value_lists_id_delete
components:
  examples:
    value_list_update_simple:
      summary: Simple
      value:
        name: Value List Name
    value_list_create_full:
      summary: Full
      value:
        name: Value List Name
        key_id: 1
        description: Value list description
        free_values:
        - value-one
        - value-two
        value_ids:
        - 1
        - 2
    value_list_create_simple:
      summary: Simple
      value:
        name: Value List Name
        key_id: 1
    value_list_update_full:
      summary: Full
      value:
        name: Value List Name
        description: Value list description
        free_values:
        - value-one
        - value-two
        value_ids:
        - 1
        - 2
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
