openapi: 3.2.0
info:
  title: SpringServe UI Creatives Tag API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Creatives Tag
paths:
  /api/v1/tag_creatives:
    get:
      tags:
      - Creatives Tag
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagCreativeIndexResponse'
      operationId: tag_creatives_get
    post:
      tags:
      - Creatives Tag
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreativeCreateData'
            examples:
              simple:
                $ref: '#/components/examples/tag_creative_create_simple'
              full:
                $ref: '#/components/examples/tag_creative_create_full'
        required: true
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagCreativeResponse'
      operationId: tag_creatives_post
  /api/v1/tag_creatives/{id}:
    get:
      tags:
      - Creatives Tag
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/includeParam
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagCreativeResponse'
      operationId: tag_creatives_id_get
    patch:
      tags:
      - Creatives Tag
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/includeParam
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreativeUpdateData'
            examples:
              simple:
                $ref: '#/components/examples/tag_creative_update_simple'
              full:
                $ref: '#/components/examples/tag_creative_update_full'
        required: false
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagCreativeResponse'
      operationId: tag_creatives_id_patch
    delete:
      tags:
      - Creatives Tag
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
        '422':
          $ref: ref/errors.yaml#/components/responses/validationError
      operationId: tag_creatives_id_delete
components:
  examples:
    tag_creative_update_full:
      summary: Full
      value:
        name: Tag Creative Name
        vast_endpoint_url: https://staging-tv.springserve.com/vast
        creative_landing_page_url: https://ad.example.com/landing
        advertiser_domain: example.com
        code: tag-code
        secondary_code: tag-secondary
        line_item_demand_tag_ids:
        - 1
        iab_tier_1_category_codes:
        - IAB1
        iab_tier_2_category_codes:
        - IAB1-1
        tag_pixels:
        - pixel_type: AdImpression
          pixel_format: image
          pixel_url: https://pixel.example.com/imp
        country_list_ids:
        - 1
        country_source: list
        state_list_ids:
        - 1
        state_source: list
        city_list_ids:
        - 1
        city_source: list
        metro_area_list_ids:
        - 1
        metro_area_source: list
        postal_code_list_ids:
        - 1
        postal_code_source: list
        frequency_caps:
        - frequency_cap_period: day
          frequency_cap_period_amount: 1
          frequency_cap_metric: impressions
          frequency_cap_value: 1
          frequency_cap_type: springserve
        key_value_targeting: true
        targeted_macros_enabled: true
        budget_timezone: America/New_York
        budgets:
        - budget_period: day
          budget_metric: impressions
          budget_value: 1
          budget_pacing: smooth
        start_date: '2026-01-01'
        end_date: '2026-12-31'
        flight_dates_timezone: America/New_York
        is_active: true
    tag_creative_create_full:
      summary: Full
      value:
        name: Tag Creative Name
        demand_partner_id: 1
        vast_endpoint_url: https://staging-tv.springserve.com/vast
        creative_format: video
        creative_landing_page_url: https://ad.example.com/landing
        advertiser_domain: example.com
        code: tag-code
        secondary_code: tag-secondary
        line_item_demand_tag_ids:
        - 1
        iab_tier_1_category_codes:
        - IAB1
        iab_tier_2_category_codes:
        - IAB1-1
        tag_pixels:
        - pixel_type: AdImpression
          pixel_format: image
          pixel_url: https://pixel.example.com/imp
        country_list_ids:
        - 1
        country_source: list
        country_white_list: true
        state_list_ids:
        - 1
        state_source: list
        city_list_ids:
        - 1
        city_source: list
        metro_area_list_ids:
        - 1
        metro_area_source: list
        postal_code_list_ids:
        - 1
        postal_code_source: list
        frequency_caps:
        - frequency_cap_period: day
          frequency_cap_period_amount: 1
          frequency_cap_metric: impressions
          frequency_cap_value: 1
          frequency_cap_type: springserve
        key_value_targeting: true
        targeted_macros_enabled: true
        user_agent_devices:
        - desktop
        all_user_agent_devices: false
        user_agent_operating_systems:
        - Windows
        all_user_agent_operating_systems: false
        user_agent_browsers:
        - Chrome
        all_user_agent_browsers: false
        user_agent_brands:
        - '1'
        all_user_agent_brands: false
        budget_timezone: America/New_York
        budgets:
        - budget_period: day
          budget_metric: impressions
          budget_value: 1
          budget_pacing: smooth
        start_date: '2026-01-01'
        end_date: '2026-12-31'
        flight_dates_timezone: America/New_York
        day_parting_users_timezone: true
        is_active: true
    tag_creative_update_simple:
      summary: Simple
      value:
        name: Tag Creative Name
        vast_endpoint_url: https://staging-tv.springserve.com/vast
        is_active: true
    tag_creative_create_simple:
      summary: Simple
      value:
        name: Tag Creative Name
        demand_partner_id: 1
        vast_endpoint_url: https://staging-tv.springserve.com/vast
  schemas:
    TagCreativeIndexResponse:
      allOf:
      - $ref: ref/params.yaml#/components/schemas/ParamsResponse
      - type: object
        properties:
          results:
            type: array
            items:
              $ref: '#/components/schemas/TagCreativeResponse'
    TagCreativeUpdateData:
      $ref: '#/components/schemas/TagCreativeBaseProperties'
    TagCreativeCreateData:
      allOf:
      - $ref: '#/components/schemas/TagCreativeBaseProperties'
      - type: object
        required:
        - demand_partner_id
        properties:
          demand_partner_id:
            type: number
    TagCreativeBaseProperties:
      allOf:
      - type: object
        properties:
          name:
            type: string
          is_active:
            type: boolean
            default: true
          vast_endpoint_url:
            type: string
          code:
            type:
            - string
            - 'null'
          secondary_code:
            type:
            - string
            - 'null'
          line_item_demand_tag_ids:
            type: array
            items:
              type: number
          iab_tier_1_category_codes:
            type: array
            items:
              type: string
          iab_tier_2_category_codes:
            type: array
            items:
              type: string
          postal_codes:
            type: array
            items:
              type: string
          postal_code_list_ids:
            type: array
            items:
              type: number
          postal_code_source:
            type: string
          postal_code_white_list:
            type: string
          key_value_targeting:
            type: boolean
          targeted_macros_enabled:
            type: boolean
          all_user_agent_devices:
            type: boolean
          all_user_agent_operating_systems:
            type: boolean
          all_user_agent_browsers:
            type: boolean
          all_user_agent_brands:
            type: boolean
          budget_timezone:
            type: string
          budgets:
            type: array
            items:
              type: object
          day_parting:
            type:
            - array
            - 'null'
            items:
              type: array
              items:
                type: boolean
          day_parting_users_timezone:
            type: boolean
          advertiser_domain:
            type:
            - string
            - 'null'
          creative_landing_page_url:
            type:
            - string
            - 'null'
          creative_format:
            type: string
      - $ref: ref/concerns/tag_pixels.yaml#/components/schemas/TagPixels
      - $ref: ref/concerns/country_codes.yaml#/components/schemas/CountryCodes
      - $ref: ref/concerns/state_codes.yaml#/components/schemas/StateCodes
      - $ref: ref/concerns/metro_area_codes.yaml#/components/schemas/MetroAreaCodes
      - $ref: ref/concerns/city_codes.yaml#/components/schemas/CityCodes
      - $ref: ref/concerns/frequency_caps.yaml#/components/schemas/FrequencyCaps
      - $ref: ref/concerns/demand_key_value.yaml#/components/schemas/DemandKeyValue
      - $ref: ref/concerns/targeted_macro.yaml#/components/schemas/TargetedMacro
      - $ref: ref/concerns/user_agent.yaml#/components/schemas/UserAgent
      - $ref: ref/concerns/flight_dates.yaml#/components/schemas/FlightDates
    TagCreativeResponse:
      allOf:
      - $ref: '#/components/schemas/TagCreativeBaseProperties'
      - type: object
        properties:
          id:
            type: integer
          account_id:
            type: integer
          demand_partner_id:
            type: integer
          type:
            type: string
          netflix_pre_approval_enabled:
            type: boolean
          netflix_approval_status:
            type:
            - string
            - 'null'
          netflix_deal_ids:
            type: array
            items:
              type: string
      - $ref: ref/concerns/timestamps.yaml#/components/schemas/Timestamps
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
