openapi: 3.2.0
info:
  title: SpringServe UI Notifications API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Notifications
paths:
  /api/v1/notifications/account:
    get:
      summary: Get account notifications
      description: Get notifications for current account of current user
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_account_get
  /api/v1/notifications/user:
    get:
      summary: Get users notification
      description: Get notifications for current user
      parameters:
      - name: include_read
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_user_get
  /api/v1/notifications/user/mark-read:
    put:
      summary: Mark all user notifications as read
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_user_mark-read_put
  /api/v1/notifications/user/mark-unread:
    put:
      summary: Mark all user notifications as unread
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_user_mark-unread_put
  /api/v1/notifications/user/{id}:
    get:
      summary: Get user notification by ID
      description: Get notification by notification ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_user_id_get
  /api/v1/notifications/user/{id}/mark-read:
    put:
      summary: Mark user notification as read
      description: Mark user notification with given ID as read
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_user_id_mark-read_put
  /api/v1/notifications/user/{id}/mark-unread:
    put:
      summary: Mark user notification as unread
      description: Mark user notification with given ID as unread
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Notifications
      operationId: notifications_user_id_mark-unread_put
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
