openapi: 3.2.0
info:
  title: SpringServe UI ISP Lists API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: ISP Lists
paths:
  /api/v1/isp_lists:
    get:
      tags:
      - ISP Lists
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_get
    post:
      tags:
      - ISP Lists
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/isp_list_create_simple'
              full:
                $ref: '#/components/examples/isp_list_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_post
  /api/v1/isp_lists/{id}:
    get:
      tags:
      - ISP Lists
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_get
    patch:
      tags:
      - ISP Lists
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/isp_list_update_simple'
              full:
                $ref: '#/components/examples/isp_list_update_full'
        required: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_patch
    delete:
      tags:
      - ISP Lists
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      operationId: isp_lists_id_delete
  /api/v1/isp_lists/permissions:
    get:
      summary: Collection Permissions
      tags:
      - ISP Lists
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_permissions_get
  /api/v1/isp_lists/{id}/isp_names:
    get:
      tags:
      - ISP Lists
      summary: ISP Names
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_get
  /api/v1/isp_lists/{id}/permissions:
    get:
      summary: Permissions Member
      tags:
      - ISP Lists
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_permissions_get
  /api/v1/isp_lists/{id}/isp_names/bulk_create:
    post:
      tags:
      - ISP Lists
      summary: Add ISPs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/isp_list_isp_names_bulk_create_single'
              multiple:
                $ref: '#/components/examples/isp_list_isp_names_bulk_create_multiple'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_bulk_create_post
  /api/v1/isp_lists/{id}/isp_names/bulk_delete:
    delete:
      tags:
      - ISP Lists
      summary: Delete ISPs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              isp_names:
              - Akamai Technologies
              - iCloud Private Relay
              - Verizon Internet Services
            schema:
              type: object
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_bulk_delete_delete
  /api/v1/isp_lists/{id}/isp_names/bulk_replace:
    post:
      tags:
      - ISP Lists
      summary: Replace ISPs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/isp_list_isp_names_bulk_replace_single'
              multiple:
                $ref: '#/components/examples/isp_list_isp_names_bulk_replace_multiple'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_bulk_replace_post
  /api/v1/isp_lists/{id}/isp_names/file_bulk_create:
    post:
      tags:
      - ISP Lists
      summary: Add ISPs (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_file_bulk_create_post
  /api/v1/isp_lists/{id}/isp_names/file_bulk_delete:
    delete:
      tags:
      - ISP Lists
      summary: Remove ISPs (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_file_bulk_delete_delete
  /api/v1/isp_lists/{id}/isp_names/file_bulk_replace:
    post:
      tags:
      - ISP Lists
      summary: Replace ISPs (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: isp_lists_id_isp_names_file_bulk_replace_post
components:
  examples:
    isp_list_isp_names_bulk_create_single:
      summary: Single
      value:
        isp_names:
        - Akamai Technologies
    isp_list_isp_names_bulk_replace_multiple:
      summary: Multiple
      value:
        isp_names:
        - Akamai Technologies
        - Verizon Internet Services
        - iCloud Private Relay
    isp_list_create_simple:
      summary: Simple
      value:
        name: ISP List Name
    isp_list_update_simple:
      summary: Simple
      value:
        name: ISP List Name
    isp_list_update_full:
      summary: Full
      value:
        name: ISP List Name
        description: ISP list description
        is_active: true
        isp_names:
        - Akamai Technologies
        - Verizon Internet Services
    isp_list_create_full:
      summary: Full
      value:
        name: ISP List Name
        description: ISP list description
        is_active: true
        isp_names:
        - Akamai Technologies
        - Verizon Internet Services
    isp_list_isp_names_bulk_replace_single:
      summary: Single
      value:
        isp_names:
        - Akamai Technologies
    isp_list_isp_names_bulk_create_multiple:
      summary: Multiple
      value:
        isp_names:
        - Akamai Technologies
        - Verizon Internet Services
        - iCloud Private Relay
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
