openapi: 3.2.0
info:
  title: SpringServe UI Supply Name Lists API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Supply Name Lists
paths:
  /api/v1/supply_name_lists:
    get:
      tags:
      - Supply Name Lists
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_get
    post:
      tags:
      - Supply Name Lists
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/supply_name_list_create_simple'
              full:
                $ref: '#/components/examples/supply_name_list_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_post
  /api/v1/supply_name_lists/{id}:
    get:
      tags:
      - Supply Name Lists
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_get
    patch:
      tags:
      - Supply Name Lists
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/supply_name_list_update_simple'
              full:
                $ref: '#/components/examples/supply_name_list_update_full'
        required: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_patch
    delete:
      tags:
      - Supply Name Lists
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      operationId: supply_name_lists_id_delete
  /api/v1/supply_name_lists/permissions:
    get:
      summary: Collection Permissions
      tags:
      - Supply Name Lists
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_permissions_get
  /api/v1/supply_name_lists/{id}/permissions:
    get:
      summary: Permissions Member
      tags:
      - Supply Name Lists
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_permissions_get
  /api/v1/supply_name_lists/{id}/supply_names:
    get:
      tags:
      - Supply Name Lists
      summary: Supply Names
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_get
  /api/v1/supply_name_lists/{id}/supply_names/bulk_create:
    post:
      tags:
      - Supply Name Lists
      summary: Add Supply Names
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/supply_name_list_supply_names_bulk_create_single'
              multiple:
                $ref: '#/components/examples/supply_name_list_supply_names_bulk_create_multiple'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_bulk_create_post
  /api/v1/supply_name_lists/{id}/supply_names/bulk_delete:
    delete:
      tags:
      - Supply Name Lists
      summary: Delete Supply Names
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              supply_names:
              - Test Publisher 1
              - Test Publisher 2
            schema:
              type: object
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_bulk_delete_delete
  /api/v1/supply_name_lists/{id}/supply_names/bulk_replace:
    post:
      tags:
      - Supply Name Lists
      summary: Replace Supply Names
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/supply_name_list_supply_names_bulk_replace_single'
              multiple:
                $ref: '#/components/examples/supply_name_list_supply_names_bulk_replace_multiple'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_bulk_replace_post
  /api/v1/supply_name_lists/{id}/supply_names/file_bulk_create:
    post:
      tags:
      - Supply Name Lists
      summary: Add Publishers Names (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_file_bulk_create_post
  /api/v1/supply_name_lists/{id}/supply_names/file_bulk_delete:
    delete:
      tags:
      - Supply Name Lists
      summary: Remove Supply Names (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_file_bulk_delete_delete
  /api/v1/supply_name_lists/{id}/supply_names/file_bulk_replace:
    post:
      tags:
      - Supply Name Lists
      summary: Replace Supply Names (CSV)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: supply_name_lists_id_supply_names_file_bulk_replace_post
components:
  examples:
    supply_name_list_supply_names_bulk_replace_multiple:
      summary: Multiple
      value:
        supply_names:
        - Publisher Name One
        - Publisher Name Two
        - Publisher Name Three
    supply_name_list_supply_names_bulk_create_single:
      summary: Single
      value:
        supply_names:
        - Publisher Name One
    supply_name_list_supply_names_bulk_replace_single:
      summary: Single
      value:
        supply_names:
        - Publisher Name One
    supply_name_list_create_full:
      summary: Full
      value:
        name: Supply Name List Name
        description: Supply name list description
        active: true
        streaming_seller_seat_ids:
        - 1
        - 2
    supply_name_list_update_simple:
      summary: Simple
      value:
        name: Supply Name List Name
    supply_name_list_create_simple:
      summary: Simple
      value:
        name: Supply Name List Name
    supply_name_list_supply_names_bulk_create_multiple:
      summary: Multiple
      value:
        supply_names:
        - Publisher Name One
        - Publisher Name Two
        - Publisher Name Three
    supply_name_list_update_full:
      summary: Full
      value:
        name: Supply Name List Name
        description: Supply name list description
        active: true
        streaming_seller_seat_ids:
        - 1
        - 2
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
