openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Forecast API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Forecast
paths:
  /api/v0/forecast:
    post:
      summary: Create Forecast
      description: Create a forecast
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Forecast
      operationId: forecast_post
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
