openapi: 3.2.0
info:
  title: SpringServe UI Report Templates API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Report Templates
paths:
  /api/v1/reports/templates:
    get:
      tags:
      - Report Templates
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      operationId: reports_templates_get
    post:
      tags:
      - Report Templates
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reportTemplate'
            examples:
              report_template_create_simple:
                $ref: '#/components/examples/report_template_create_simple'
              report_template_create_full:
                $ref: '#/components/examples/report_template_create_full'
        required: true
      responses:
        '201':
          $ref: '#/components/responses/reportTemplate'
        '422':
          description: ''
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/reportParameterError'
                - $ref: ref/errors.yaml#/components/schemas/validationError
      operationId: reports_templates_post
  /api/v1/reports/templates/{id}:
    get:
      tags:
      - Report Templates
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      summary: Show
      responses:
        '200':
          $ref: '#/components/responses/reportTemplate'
        '404':
          $ref: ref/errors.yaml#/components/responses/notFoundError
        '500':
          $ref: '#/components/responses/reportSerializationError'
      operationId: reports_templates_id_get
    patch:
      tags:
      - Report Templates
      summary: Update
      description: 'NOTE: This operation will overwrite and/or delete already existing parameters in the report template. Make sure

        that everything that should be in the report template is specified in the request body.'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reportTemplate'
            examples:
              report_template_update_simple:
                $ref: '#/components/examples/report_template_update_simple'
              report_template_update_full:
                $ref: '#/components/examples/report_template_update_full'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/reportTemplate'
        '400':
          $ref: '#/components/responses/reportParameterError'
        '404':
          $ref: ref/errors.yaml#/components/responses/notFoundError
        '422':
          $ref: ref/errors.yaml#/components/responses/validationError
        '500':
          $ref: '#/components/responses/reportSerializationError'
      operationId: reports_templates_id_patch
    delete:
      tags:
      - Report Templates
      summary: Delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No content
        '404':
          $ref: ref/errors.yaml#/components/responses/notFoundError
      operationId: reports_templates_id_delete
  /api/v1/reports/templates/{id}/set_default:
    post:
      tags:
      - Report Templates
      summary: Set as default
      description: Sets the authenticated user's default report template to this template.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success with an empty body.
          content:
            application/json:
              schema:
                type: object
        '404':
          $ref: ref/errors.yaml#/components/responses/notFoundError
        '422':
          $ref: ref/errors.yaml#/components/responses/validationError
      operationId: reports_templates_id_set_default_post
components:
  examples:
    report_template_update_simple:
      summary: Simple
      value:
        name: Report Template Name
    report_template_create_full:
      summary: Full
      value:
        name: Report Template Name
        description: My report template
        date_range: Last 7 Days
        interval: day
        interval_start_day: monday
        timezone: America/New_York
        currency: USD
        dimensions:
        - supply_partner_id
        - supply_tag_id
        metrics:
        - usable_requests
        - fill_rate
        filters:
        - dimension: supply_partner_id
          type: values
          values:
          - 1
          is_include: true
          is_exact_match: false
        having:
        - metric: usable_requests
          max: false
          value: 1
    report_template_create_simple:
      summary: Simple
      value:
        name: Report Template Name
        date_range: Yesterday
        dimensions:
        - supply_partner_id
        metrics:
        - usable_requests
    report_template_update_full:
      summary: Full
      value:
        name: Report Template Name
        description: Updated report template
        date_range: Last 7 Days
        interval: day
        interval_start_day: monday
        timezone: America/New_York
        currency: USD
        dimensions:
        - supply_partner_id
        - supply_tag_id
        metrics:
        - usable_requests
        - fill_rate
        filters:
        - dimension: supply_partner_id
          type: values
          values:
          - 1
          is_include: true
          is_exact_match: false
  schemas:
    reportParameterError:
      type: object
      properties:
        error:
          type: string
          examples:
          - 'Could not parse report parameters: ...'
    reportSerializationError:
      type: object
      properties:
        error:
          type: string
          examples:
          - 'Could not serialize report template with /api/v1 format: ...'
    reportTemplate:
      allOf:
      - $ref: ref/reports.yaml#/components/schemas/reportParameters
      - type: object
        properties:
          id:
            type: integer
            readOnly: true
          name:
            type: string
          description:
            type: string
          created_at:
            type: string
            readOnly: true
          updated_at:
            type: string
            readOnly: true
      examples:
      - id: 1
        name: Example Report Template
        date_range: Yesterday
        interval: null
        dimensions:
        - supply_partner_id
        - supply_tag_id
        filters:
        - dimension: supply_partner_id
          type: values
          values:
          - 1
          - 2
          - 3
          is_include: true
          is_exact_match: false
        metrics:
        - usable_requests
  responses:
    reportParameterError:
      description: Report Parameter Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/reportParameterError'
    reportSerializationError:
      description: Report Serialization Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/reportSerializationError'
    reportTemplate:
      description: A report template
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/reportTemplate'
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
